name: flutter_ddd
description: Core tools for DDD
version: 0.0.1
homepage: https://github.com/Afflya/flutter_ddd

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.4"

dependencies:
  dartz: '>=0.10.0'
  flutter:
    sdk: flutter
  uuid: '>=3.0.5'

dev_dependencies:
  build_runner: '>=2.2.0'
  flutter_test:
    sdk: flutter
  lint: '>=1.5.3-0 <1.6.0'

flutter:

